apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: myapp
  labels:
    app: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 2
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: 914379829654.dkr.ecr.us-east-1.amazonaws.com/web_app:v0.3
        env:
        - name: DBHOST
          value: "mysql.lab3"
        - name: DBPORT
          value: "3306"  
        - name: DBUSER
          value: "root"
        - name: DATABASE
          value: "employees"
        - name: DBPWD
          value: "pw"
        - name: APP_COLOR
          valueFrom:
            configMapKeyRef:
                name: colorapp-config
                key: APP_COLOR
        ports:
        - name: webapp
          containerPort: 8080