apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-hostpath
  labels:
    app: mysql-hostpath
spec:
  storageClassName: localstorage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
