apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc 
  namespace: lab3
  annotations:
    volume.beta.kubernetes.io/storage-class: standard
spec:
  storageClassName: standard
  resources:
    requests:
      storage: 4Gi
  accessModes:
    - ReadWriteOnce
