apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
  namespace: lab3
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: < Image URI >
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: pw
        - name: DBPWD
            value: "pw"
        - name: DBUSER
            value: "root"
          
        ports:
        - containerPort: 3306
        - name: mysql
        - protocol: TCP
        volumeMounts:
        - name: mysql-pvc
          mountPath: /var/lib/mysql
      volumes:
        - name: mysql-pvc
          persistentVolumeClaim:
            claimName: mysql-pvc
