apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: lab3
spec:
  resources:
    requests:
      storage: 4Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: "localstorage"
  hostPath:
    path: "/tmp/data"
